#!/usr/bin/env python3
# from http://robjwells.com/post/57241647827/commit-summary-length-hooks

import sys

message = open(sys.argv[1])
summary_length = len(message.readline().splitlines()[0])

if summary_length > 50:
  print("\x1b[31m[!] Commit summary is too long (> 50c)\x1b[0m")
  sys.exit(1)
