#!/bin/sh
# courtesy of http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html
# modified by https://github.com/richo/git_template/blob/master/hooks/ctags
mkdir .git/tags_lock 2>/dev/null || exit 0
trap "rmdir .git/tags_lock; rm .git/tags.$$" EXIT

ctags --tag-relative -R -f .git/tags.$$ --exclude=.git --languages=-sql,-css,-javascript
mv .git/tags.$$ .git/tags
